# Use custom format

format = """
$username$hostname$vagrant$terraform$elixir$ruby$go$nodejs$git_branch${custom.tailscale}$directory${custom.remote}$character
"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

command_timeout = 2000

# Disable the blank line at the start of the prompt
add_newline = false

[character]
success_symbol = "[❯](bold green)"

[git_branch]
symbol = "🌱 "
truncation_length = 10
truncation_symbol = ""

[docker_context]
format = "via [🐋 $context](blue bold) "

[ruby]
format = "ruby [$version](red bold) "
detect_variables	= []

[nodejs]
format = "node [$version](green bold) "

[hostname]
ssh_only = false
format = "@[$hostname](green bold) "

[username]
show_always = true
format = "[$user](yellow bold)"

[directory]
format = "[$path](cyan bold) "
truncate_to_repo = true
truncation_length=1

[localip]
disabled=false
ssh_only=false

[custom.tailscale]
format = "TS: [$output](yellow bold) "
description = "Tailscale 1P"
when = true
command = "tailscale ip --4"

[custom.remote]
command = "echo REMOTE"
when = "test -n \"$SSH_CONNECTION\""
format = "[🚨 $output 🚨](bold red) "
